<a href="https://colab.research.google.com/github/anas1IA/MLP-Hyperparameters-optimization/blob/main/MLP_optimizations_num_of_neurons.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [84]:
import pandas as pd
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as  f
from sklearn.model_selection  import train_test_split

In [85]:
data = pd.read_csv("Iris.csv")
data.tail()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica

In [86]:
data.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [87]:
data["Species"].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [88]:
data.shape

(150, 6)

In [89]:
data = data.drop(columns= "Id")

In [90]:
data['Species'] = data['Species'].replace('Iris-setosa',0.0)
data['Species'] = data['Species'].replace('Iris-versicolor',1.0)
data['Species'] = data['Species'].replace('Iris-virginica',2.0)

In [91]:
data

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0              5.1           3.5            1.4           0.2      0.0
1              4.9           3.0            1.4           0.2      0.0
2              4.7           3.2            1.3           0.2      0.0
3              4.6           3.1            1.5           0.2      0.0
4              5.0           3.6            1.4           0.2      0.0
..             ...           ...            ...           ...      ...
145            6.7           3.0            5.2           2.3      2.0
146            6.3           2.5            5.0           1.9      2.0
147            6.5           3.0            5.2           2.0      2.0
148            6.2           3.4            5.4           2.3      2.0
149            5.9           3.0            5.1           1.8      2.0

[150 rows x 5 columns]

In [92]:
X = data.drop('Species',axis=1)
y = data['Species']
X

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0              5.1           3.5            1.4           0.2
1              4.9           3.0            1.4           0.2
2              4.7           3.2            1.3           0.2
3              4.6           3.1            1.5           0.2
4              5.0           3.6            1.4           0.2
..             ...           ...            ...           ...
145            6.7           3.0            5.2           2.3
146            6.3           2.5            5.0           1.9
147            6.5           3.0            5.2           2.0
148            6.2           3.4            5.4           2.3
149            5.9           3.0            5.1           1.8

[150 rows x 4 columns]

In [93]:
# convert thesse to numpy array
X = X.values
y = y.values


In [94]:
X.dtype

dtype('float64')

In [95]:
X ,y

(array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
        [5

In [96]:
X_train ,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)
y_train

array([0., 0., 2., 1., 0., 2., 1., 2., 1., 0., 2., 0., 2., 1., 2., 2., 0.,
       1., 2., 1., 2., 1., 1., 2., 0., 0., 2., 1., 1., 0., 0., 2., 0., 1.,
       0., 1., 0., 2., 1., 2., 1., 1., 1., 1., 0., 1., 0., 2., 2., 1., 0.,
       1., 1., 2., 1., 2., 2., 0., 0., 0., 2., 2., 0., 1., 0., 2., 1., 0.,
       2., 2., 1., 1., 2., 2., 2., 0., 1., 0., 0., 0., 0., 0., 1., 2., 2.,
       1., 2., 0., 0., 1., 1., 2., 2., 2., 2., 2., 0., 2., 0., 1., 1., 2.,
       2., 0., 2., 0., 1., 2., 1., 1., 2., 0., 0., 1., 2., 2., 2., 0., 2.,
       0.])

In [97]:
#convert features to tensors
X_train = torch.FloatTensor(X_train)
X_test= torch.FloatTensor(X_test)
X_train

tensor([[5.7000, 3.8000, 1.7000, 0.3000],
        [4.8000, 3.0000, 1.4000, 0.1000],
        [5.8000, 2.8000, 5.1000, 2.4000],
        [6.1000, 2.9000, 4.7000, 1.4000],
        [5.5000, 4.2000, 1.4000, 0.2000],
        [6.5000, 3.0000, 5.5000, 1.8000],
        [5.8000, 2.7000, 4.1000, 1.0000],
        [6.5000, 3.0000, 5.8000, 2.2000],
        [5.5000, 2.6000, 4.4000, 1.2000],
        [5.0000, 3.2000, 1.2000, 0.2000],
        [6.7000, 3.3000, 5.7000, 2.1000],
        [5.1000, 3.7000, 1.5000, 0.4000],
        [6.4000, 3.1000, 5.5000, 1.8000],
        [5.6000, 2.9000, 3.6000, 1.3000],
        [7.7000, 3.8000, 6.7000, 2.2000],
        [6.3000, 2.8000, 5.1000, 1.5000],
        [5.5000, 3.5000, 1.3000, 0.2000],
        [5.8000, 2.6000, 4.0000, 1.2000],
        [7.7000, 3.0000, 6.1000, 2.3000],
        [5.6000, 3.0000, 4.1000, 1.3000],
        [6.9000, 3.1000, 5.1000, 2.3000],
        [5.4000, 3.0000, 4.5000, 1.5000],
        [6.6000, 2.9000, 4.6000, 1.3000],
        [7.7000, 2.8000, 6.7000, 2

In [98]:
# convert labels to long values
y_train = torch.LongTensor(y_train)
y_test = torch.LongTensor(y_test)
y_train

tensor([0, 0, 2, 1, 0, 2, 1, 2, 1, 0, 2, 0, 2, 1, 2, 2, 0, 1, 2, 1, 2, 1, 1, 2,
        0, 0, 2, 1, 1, 0, 0, 2, 0, 1, 0, 1, 0, 2, 1, 2, 1, 1, 1, 1, 0, 1, 0, 2,
        2, 1, 0, 1, 1, 2, 1, 2, 2, 0, 0, 0, 2, 2, 0, 1, 0, 2, 1, 0, 2, 2, 1, 1,
        2, 2, 2, 0, 1, 0, 0, 0, 0, 0, 1, 2, 2, 1, 2, 0, 0, 1, 1, 2, 2, 2, 2, 2,
        0, 2, 0, 1, 1, 2, 2, 0, 2, 0, 1, 2, 1, 1, 2, 0, 0, 1, 2, 2, 2, 0, 2, 0])

In [99]:

class Model(nn.Module):

    def __init__(self,in_features = 4,h1 = 8 ,h2 =9 ,output = 3):
      super().__init__()
      #self.fc1=nn.Linear(in_features ,h1)
      #self.fc2=nn.Linear(h1,h2)
      #self.out=nn.Linear(h2,output)
      self.two_Layers = nn.Sequential(nn.Linear(in_features ,h1),
      nn.ReLU(),nn.Linear(h1 ,h2), nn.ReLU() ,nn.Linear(h2 ,output))

    #def forward(self , x):
      # return f.relu(self.out(f.relu(self.fc1(x))))

    def forward(self ,x):
      return self.two_Layers(x)



In [100]:
model = Model()


In [101]:
critersion = nn.CrossEntropyLoss()

In [102]:

optimizar = torch.optim.Adam(model.parameters(),lr = 0.01)
y_train

tensor([0, 0, 2, 1, 0, 2, 1, 2, 1, 0, 2, 0, 2, 1, 2, 2, 0, 1, 2, 1, 2, 1, 1, 2,
        0, 0, 2, 1, 1, 0, 0, 2, 0, 1, 0, 1, 0, 2, 1, 2, 1, 1, 1, 1, 0, 1, 0, 2,
        2, 1, 0, 1, 1, 2, 1, 2, 2, 0, 0, 0, 2, 2, 0, 1, 0, 2, 1, 0, 2, 2, 1, 1,
        2, 2, 2, 0, 1, 0, 0, 0, 0, 0, 1, 2, 2, 1, 2, 0, 0, 1, 1, 2, 2, 2, 2, 2,
        0, 2, 0, 1, 1, 2, 2, 0, 2, 0, 1, 2, 1, 1, 2, 0, 0, 1, 2, 2, 2, 0, 2, 0])

In [103]:
 y_pred = model.forward(X_train)
 y_pred

tensor([[-0.2681,  0.5322,  0.5232],
        [-0.2545,  0.4509,  0.4099],
        [-0.3670,  0.5446,  0.3818],
        [-0.3100,  0.5479,  0.4456],
        [-0.2938,  0.5162,  0.5310],
        [-0.3476,  0.5651,  0.4520],
        [-0.2744,  0.5295,  0.4372],
        [-0.3737,  0.5684,  0.4345],
        [-0.2954,  0.5023,  0.3835],
        [-0.2575,  0.4734,  0.4396],
        [-0.3705,  0.5881,  0.4730],
        [-0.2726,  0.5018,  0.4715],
        [-0.3521,  0.5594,  0.4440],
        [-0.2793,  0.5457,  0.4443],
        [-0.4016,  0.6389,  0.5531],
        [-0.3207,  0.5506,  0.4443],
        [-0.2616,  0.5079,  0.4953],
        [-0.2766,  0.5381,  0.4375],
        [-0.3649,  0.6497,  0.5551],
        [-0.2984,  0.5301,  0.4228],
        [-0.3499,  0.6270,  0.5175],
        [-0.3234,  0.5084,  0.3789],
        [-0.2931,  0.5847,  0.5080],
        [-0.3670,  0.6154,  0.5203],
        [-0.2581,  0.5010,  0.4771],
        [-0.2643,  0.4823,  0.4548],
        [-0.3404,  0.5611,  0.4427],
 

In [104]:
epochs = 120
losses = []
for i in range(epochs) :
  y_pred = model.forward(X_train) # Get the prdiction
  loss = critersion( y_pred ,y_train) # clacul error between y_predict and y_test
  losses.append(loss.detach().numpy)
  # print result for each 10 iterations:
  if i % 10 == 0:
    print(f"epoch : {i} and loss : {loss}")
  optimizar.zero_grad()
  loss.backward()
  optimizar.step()




epoch : 0 and loss : 1.1361745595932007
epoch : 10 and loss : 0.9392480254173279
epoch : 20 and loss : 0.6277430653572083
epoch : 30 and loss : 0.39528560638427734
epoch : 40 and loss : 0.2590028643608093
epoch : 50 and loss : 0.14614754915237427
epoch : 60 and loss : 0.07828839868307114
epoch : 70 and loss : 0.047560468316078186
epoch : 80 and loss : 0.03337503597140312
epoch : 90 and loss : 0.02590274251997471
epoch : 100 and loss : 0.02140192873775959
epoch : 110 and loss : 0.018369095399975777
